const express = require('express');
const contentTypeController = require('../controllers/contentType');
const contentTypeRouter =express.Router();
const {generateValidationMiddleware} = require('../middleware/validation');
const  Schema = require('../../src/schemas/contentType');
const {authenticateToken} = require('../middleware/authenticate');
contentTypeRouter.post('/', authenticateToken,generateValidationMiddleware(Schema.createContentTypeSchema),contentTypeController.createContentType);
contentTypeRouter.get('/all',authenticateToken, contentTypeController.getAllContentTypes);
contentTypeRouter.get('/:id',authenticateToken,generateValidationMiddleware(Schema.getParamsSchema,'params') ,contentTypeController.getContentById);
contentTypeRouter.put('/:id', authenticateToken,generateValidationMiddleware(Schema.updateContentTypeSchema),contentTypeController.updateContentType);
contentTypeRouter.delete('/:id',authenticateToken, generateValidationMiddleware(Schema.deleteParamsSchema,'params'),contentTypeController.deleteContentType);
module.exports=contentTypeRouter;